"""add package to chunks

Revision ID: 0ff7f14d71a4
Revises: b59e49940b60
Create Date: 2026-10-06 02:26:38.314254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff7f14d71a4'
down_revision: Union[str, Sequence[str], None] = 'b59e49940b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('package', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_chunks_package'), 'document_chunks', ['package'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_package'), table_name='document_chunks')
    op.create_index(op.f('ix_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('document_chunks', 'package')
    # ### end Alembic commands ###
